
def MadLibGen():
    adjective = str(input("Think of an adjective: ").title())
    adjective2 = str(input("\nThink of another adjective: ").title())
    birdType = str(input("\nThink of a type of Bird: ").title())
    roomInHouse = str(input("\nType of a room in a House: ").title())
    pastTenseVerb = str(input("\nPast Tense Verb: ").title())
    verb = str(input("\nThink of a normal verb: "))
    relativeName = str(input("\nThink of the name of a Relative: ").title())
    noun = str(input("\nThink of a noun: ").title())
    liquid = str(input("\nType of liquid: ").title())
    verbWithIng = str(input("\nThink of a verb that ends with ing: ").title())
    bodyPart = str(input("\nType of body part (plural): ").title())
    verbWithIng2 = str(input("\nAnother verb ending with ing: "))
    pluralNoun = str(input("\nA plural noun: "))
    noun2 = str(input("\nThink of another noun: "))

    print("\nComencing MAD-LIB-GENERATORRRR!!!!!!!!!!!!!!!!")
    print(".....")
    print("....")
    print("...")
    print("..")
    print(".")
    print("It was a " + adjective + " ,cold November day.")
    print("I woke up to the " + adjective2 + " smell of " + birdType + " roasting in the " + roomInHouse + " downstairs.")
    print("I " + pastTenseVerb + " down the stairs to see if I could help " + verb + " the dinner.")
    print("My mom said, See if " + relativeName + " needs a fresh " + noun + ".")
    print("So I carried a tray of glasses full of " + liquid + " into the " + verbWithIng + " room.")
    print("When I got there, I couldn't believe my " + bodyPart + "!")
    print("There were " + pluralNoun + " " + verbWithIng2 + " " + noun2)
MadLibGen()
